### ISSUE TITLE
输入"数字 字母"会出错

### ISSUE THREAD

**Issue by STayinloves** [duduainankai/zhihu-terminal#1]
输入"数字 字母"不会提示help而是会出错，比如下面这样
```
Time Line$ 8 b
Traceback (most recent call last):
  File "zhihu.py", line 320, in <module>
    main()
  File "zhihu.py", line 307, in main
    opn = int(op)
ValueError: invalid literal for int() with base 10: '8 b'
```

**Comment by duduainankai** [comment]
已经修复了  谢谢你的提醒。
