### ISSUE TITLE
好像不能查看完整回答

### ISSUE THREAD

**Issue by whuhan2013** [duduainankai/zhihu-terminal#2]
只能看到主页上面的显示全部这一部分，怎么进入问题查看全部。

**Comment by duduainankai** [comment]
这个异常应该是因为现在知乎的首页内容不再是通过时间来显示而开始做个性化推荐的内容了，所以原来的程序有问题了。我发现好久了但是一直没时间改 ＝＝。

然后你说进入问题查看全部回答我不是很理解：
0. 如果是想看选中的条目的完整回答的话可以输入answer；
1. 如果是想查看一个问题的所有回答的话可以在question的作用域下输入answers然后会显示所有回答的条目（也是不完整的），输入序号选中其中一个条目后用answer就可以查看完整回答了。

在任何时候都可以输入help来查看当前可以做的操作的。

**Comment by whuhan2013** [comment]
你好，输入answer后程序异常无法继续运行，运行如下：

Time Line$ 9
马前卒  赞同该回答(124赞):	1小时前
如何看待中国劳动生产率仅为美国的 7.4%？(Orz辉)
  真是大开眼界。。。 国家统计局数据表格明明写着用的是“2005年不变价格”，可某些人连“不变价格”是什么意思都搞明白，就质疑统计局的数据，还能获得1000个赞。。。 去年的钱和今年的能比么？2005年北京海淀区的房价5000块，现在5000块在通州能买到房么？…

显示全部

Time Line Item$ answer
Traceback (most recent call last):
  File "zhihu.py", line 320, in <module>
    main()
  File "zhihu.py", line 310, in main
    if item.operate():
  File "/home/jjx/Code/zhihu-terminal/TimeLine.py", line 181, in operate
    if answer.operate():
  File "/home/jjx/Code/zhihu-terminal/Answer.py", line 178, in operate
    self.get_full_answer()
  File "/home/jjx/Code/zhihu-terminal/Answer.py", line 70, in get_full_answer
    answer = item.find("div", class_="zm-editable-content clearfix")
AttributeError: 'NoneType' object has no attribute 'find'

**Comment by duduainankai** [comment]
你好，想问下是所有查看回答的情况都是这样还是只有这一个条目呢？还有在问题下查看回答的时候是否也有这个异常呢？

然后可否告知一下你的运行环境，包括操作系统和python的版本。

因为我本地运行并为出现上述的情况（如下图示），感觉有点奇怪，谢谢。

![image](https://cloud.githubusercontent.com/assets/9639449/18671559/27126726-7f77-11e6-9110-083053c8b14d.png)

**Comment by whuhan2013** [comment]
版本信息如下，所有查看答案都会出错，包括在问题下查看回答：
![t1](https://cloud.githubusercontent.com/assets/13049692/18673267/be7b4d66-7f7d-11e6-8d97-7badbff29f9c.png)
![t2](https://cloud.githubusercontent.com/assets/13049692/18673270/c1f7cc4e-7f7d-11e6-8614-0ee1d0c2ab56.png)
![t3](https://cloud.githubusercontent.com/assets/13049692/18673269/bee15336-7f7d-11e6-9158-849ad3bdc580.png)

**Comment by duduainankai** [comment]
好的，我的环境是Mac 10.10， python 2.7.11。

原先也没怎么在linux上试过，所以我可能需要找到一台linux的机器来测试一下吧，可能会晚几天了。

如果你有兴趣可以尝试找一下原因，直接修改好的话给我提pr就好，谢谢。
