### ISSUE TITLE
表单上传失败

### ISSUE THREAD

**Issue by duoduoeeee** [duduainankai/zhihu-terminal#4]
如题

```
正在为您登录...
正在为您登录...
INFO: 正在加载配置文件 ...
INFO: 提取XSRF 代码失败
INFO: 正在调用外部程序渲染验证码 ... 
INFO: Command: xdg-open verify.gif &
请输入验证码: tksp
ERROR: 网络异常
Traceback (most recent call last):
  File "zhihu.py", line 113, in <module>
    if not login():
  File "/home/Lingduo/git/zhihu-terminal/login.py", line 234, in login
    result = upload_form(form_data)
  File "/home/Lingduo/git/zhihu-terminal/login.py", line 152, in upload_form
    raise NetworkError(u"表单上传失败!")
login.NetworkError
```

系统 fedora 25 x64

困惑

**Comment by lizhemingi** [comment]
抱歉  最近开始实习了比较忙，这个项目也很久没有更新维护了。
知乎的前端也更新的我都不认识了，所以可能没有精力再去维护了，不好意思。

**Comment by duoduoeeee** [comment]
好的吧 谢谢你
